package com.example.asser.ui.theme

import androidx.compose.ui.graphics.Color

// Default Green Theme
val GreenPrimary = Color(0xFF006C45)
val GreenOnPrimary = Color(0xFFFFFFFF)
val GreenPrimaryContainer = Color(0xFF8CF7BE)
val GreenOnPrimaryContainer = Color(0xFF002112)
val GreenSecondary = Color(0xFF4E6355)
val GreenOnSecondary = Color(0xFFFFFFFF)
val GreenSecondaryContainer = Color(0xFFD1E8D6)
val GreenOnSecondaryContainer = Color(0xFF0B1F14)
val GreenTertiary = Color(0xFF3D6473)
val GreenOnTertiary = Color(0xFFFFFFFF)
val GreenTertiaryContainer = Color(0xFFC0E9FB)
val GreenOnTertiaryContainer = Color(0xFF001F28)
val GreenError = Color(0xFFBA1A1A)
val GreenErrorContainer = Color(0xFFFFDAD6)
val GreenOnError = Color(0xFFFFFFFF)
val GreenOnErrorContainer = Color(0xFF410002)
val GreenBackground = Color(0xFFFBFDF8)
val GreenOnBackground = Color(0xFF191C1A)
val GreenSurface = Color(0xFFFBFDF8)
val GreenOnSurface = Color(0xFF191C1A)
val GreenSurfaceVariant = Color(0xFFDDE5DB)
val GreenOnSurfaceVariant = Color(0xFF414943)
val GreenOutline = Color(0xFF717972)

// Dark Green Theme
val GreenDarkPrimary = Color(0xFF70DAA4)
val GreenDarkOnPrimary = Color(0xFF003822)
val GreenDarkPrimaryContainer = Color(0xFF005233)
val GreenDarkOnPrimaryContainer = Color(0xFF8CF7BE)
val GreenDarkSecondary = Color(0xFFB5CCBA)
val GreenDarkOnSecondary = Color(0xFF203528)
val GreenDarkSecondaryContainer = Color(0xFF364B3E)
val GreenDarkOnSecondaryContainer = Color(0xFFD1E8D6)
val GreenDarkTertiary = Color(0xFFA5CDDE)
val GreenDarkOnTertiary = Color(0xFF073542)
val GreenDarkTertiaryContainer = Color(0xFF244C5A)
val GreenDarkOnTertiaryContainer = Color(0xFFC0E9FB)
val GreenDarkError = Color(0xFFFFB4AB)
val GreenDarkErrorContainer = Color(0xFF93000A)
val GreenDarkOnError = Color(0xFF690005)
val GreenDarkOnErrorContainer = Color(0xFFFFDAD6)
val GreenDarkBackground = Color(0xFF191C1A)
val GreenDarkOnBackground = Color(0xFFE1E3DF)
val GreenDarkSurface = Color(0xFF191C1A)
val GreenDarkOnSurface = Color(0xFFE1E3DF)
val GreenDarkSurfaceVariant = Color(0xFF414943)
val GreenDarkOnSurfaceVariant = Color(0xFFC1C9C0)
val GreenDarkOutline = Color(0xFF8B938B)

// Blue Accent Theme
val BluePrimary = Color(0xFF0061A4)
val BlueOnPrimary = Color(0xFFFFFFFF)
val BluePrimaryContainer = Color(0xFFD1E4FF)
val BlueOnPrimaryContainer = Color(0xFF001D36)
val BlueSecondary = Color(0xFF535F70)
val BlueOnSecondary = Color(0xFFFFFFFF)
val BlueSecondaryContainer = Color(0xFFD7E3F7)
val BlueOnSecondaryContainer = Color(0xFF101C2B)
val BlueTertiary = Color(0xFF6B5778)
val BlueOnTertiary = Color(0xFFFFFFFF)
val BlueTertiaryContainer = Color(0xFFF2DAFF)
val BlueOnTertiaryContainer = Color(0xFF251431)

// Dark Blue Accent Theme
val BlueDarkPrimary = Color(0xFF9ECAFF)
val BlueDarkOnPrimary = Color(0xFF003258)
val BlueDarkPrimaryContainer = Color(0xFF00497D)
val BlueDarkOnPrimaryContainer = Color(0xFFD1E4FF)
val BlueDarkSecondary = Color(0xFFBBC7DB)
val BlueDarkOnSecondary = Color(0xFF253140)
val BlueDarkSecondaryContainer = Color(0xFF3B4858)
val BlueDarkOnSecondaryContainer = Color(0xFFD7E3F7)
val BlueDarkTertiary = Color(0xFFD6BEE4)
val BlueDarkOnTertiary = Color(0xFF3B2948)
val BlueDarkTertiaryContainer = Color(0xFF523F5F)
val BlueDarkOnTertiaryContainer = Color(0xFFF2DAFF)

// Purple Accent Theme
val PurplePrimary = Color(0xFF6750A4)
val PurpleOnPrimary = Color(0xFFFFFFFF)
val PurplePrimaryContainer = Color(0xFFEADDFF)
val PurpleOnPrimaryContainer = Color(0xFF22005D)
val PurpleSecondary = Color(0xFF625B71)
val PurpleOnSecondary = Color(0xFFFFFFFF)
val PurpleSecondaryContainer = Color(0xFFE8DEF8)
val PurpleOnSecondaryContainer = Color(0xFF1E192B)
val PurpleTertiary = Color(0xFF7D5260)
val PurpleOnTertiary = Color(0xFFFFFFFF)
val PurpleTertiaryContainer = Color(0xFFFFD8E4)
val PurpleOnTertiaryContainer = Color(0xFF31111D)

// Dark Purple Accent Theme
val PurpleDarkPrimary = Color(0xFFD0BCFF)
val PurpleDarkOnPrimary = Color(0xFF381E72)
val PurpleDarkPrimaryContainer = Color(0xFF4F378A)
val PurpleDarkOnPrimaryContainer = Color(0xFFEADDFF)
val PurpleDarkSecondary = Color(0xFFCCC2DC)
val PurpleDarkOnSecondary = Color(0xFF332D41)
val PurpleDarkSecondaryContainer = Color(0xFF4A4458)
val PurpleDarkOnSecondaryContainer = Color(0xFFE8DEF8)
val PurpleDarkTertiary = Color(0xFFEFB8C8)
val PurpleDarkOnTertiary = Color(0xFF492532)
val PurpleDarkTertiaryContainer = Color(0xFF633B48)
val PurpleDarkOnTertiaryContainer = Color(0xFFFFD8E4)
